### ISSUE TITLE
Change package name

### ISSUE THREAD

**Issue by Turhvjbufv** [Schwartzblat/WhatsAppPatcher#60] opened 2023-11-01 10:59 UTC
Currently it doesn't work in some devices since you can't entirely uninstall Whatsapp maybe if you use shizuku but that can be very complicated for people, so if you can provide a patched apk with a different package name it would be nice.

**Comment by Schwartzblat** [comment] 2023-12-15 21:36
Duplicate of #55 .

**Closed by Schwartzblat** 2023-12-15 21:36 UTC
